# Generated by Django 4.1.5 on 2023-02-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(max_length=100)),
                ('user_id', models.IntegerField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occasion', models.CharField(max_length=50)),
                ('gift_for', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InspoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(max_length=100)),
                ('user_id', models.IntegerField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(max_length=100)),
                ('user_id', models.IntegerField(max_length=100)),
                ('list_item', models.TextField(max_length=1000)),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(max_length=100)),
                ('user_id', models.IntegerField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('color_scheme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SharedBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curatorieapi.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curatorieapi.user')),
            ],
        ),
    ]
